package:
  name: fh-immuta-utils
  version: "0.0.1"

source:
  path: ../

build:
  script:
    - python -m pip install --no-deps --ignore-installed .
  entry_points:
    - fh-immuta-utils = fh_immuta_utils.scripts.cli:cli_main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - boto3
    - click
    - hvac
    - psycopg2
    - pyathena
    - pydantic
    - pyyaml
    - requests
    - six
    - sqlalchemy
    - toolz
    - tqdm
    - urllib3

test:
  requires:
    - pytest
  imports:
    - fh_immuta_utils

about:
  home: https://github.com/flatironhealth/fh-immuta-utils
  license: BSD-3
  license_family: BSD
  license_file: LICENSE.md

